# Generated by Django 6.0 on 2026-01-10 21:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4)),
                ('documento', models.CharField(help_text='CPF ou CNPJ', max_length=18, unique=True)),
                ('categoria', models.CharField(choices=[('ALUNO', 'Aluno (CPF)'), ('PROFESSOR', 'Professor (CPF)'), ('STARTUP_PF', 'Startup (CPF - Pré-formalizada)'), ('STARTUP_PJ', 'Startup (CNPJ)'), ('EMPRESA', 'Empresa (CNPJ)'), ('INSTITUICAO', 'Instituição de Ensino (CNPJ)')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=150, unique=True)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('progresso', 'Progresso'), ('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('social', 'Social')], db_index=True, max_length=20)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pontos', models.PositiveIntegerField(default=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='idx_conquista_tipo_ativo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_objetivo__gte', 0)), name='valor_objetivo_nao_negativo'), models.CheckConstraint(condition=models.Q(('pontos__gte', 0)), name='pontos_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=150, unique=True)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('mercado', 'Mercado'), ('produto', 'Produto'), ('equipe', 'Equipe'), ('investimento', 'Investimento'), ('risco', 'Risco')], db_index=True, max_length=20)),
                ('chance_base', models.DecimalField(decimal_places=3, default=Decimal('0.1'), help_text='Probabilidade entre 0 e 1.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('impacto_saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impacto_receita', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impacto_valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('impacto_funcionarios', models.IntegerField(default=0)),
                ('turno_minimo', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['categoria', 'ativo'], name='idx_categoria_ativo'), models.Index(fields=['turno_minimo', 'ativo'], name='idx_turno_ativo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('chance_base__gte', 0), ('chance_base__lte', 1)), name='chance_entre_0_e_1'), models.CheckConstraint(condition=models.Q(('turno_minimo__gte', 1)), name='evento_turno_minimo_1')],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a partida está em andamento')),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data de conclusão da partida', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField()),
                ('resolvido', models.BooleanField(db_index=True, default=False)),
                ('resultado', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='core.evento')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.partida')),
            ],
            options={
                'verbose_name': 'Evento da Partida',
                'verbose_name_plural': 'Eventos da Partida',
                'ordering': ['turno'],
            },
        ),
        migrations.CreateModel(
            name='ConquistaDesbloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField(default=1)),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueios', to='core.conquista')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='core.partida')),
            ],
            options={
                'verbose_name': 'Conquista Desbloqueada',
                'verbose_name_plural': 'Conquistas Desbloqueadas',
                'ordering': ['-desbloqueada_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDecisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao_tomada', models.TextField()),
                ('turno', models.PositiveIntegerField()),
                ('data_decisao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='core.partida')),
            ],
            options={
                'verbose_name': 'Histórico de Decisão',
                'verbose_name_plural': 'Históricos de Decisões',
                'ordering': ['turno'],
            },
        ),
        migrations.CreateModel(
            name='Fundador',
            fields=[
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fundador', serialize=False, to='core.partida')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(16)])),
                ('experiencia', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('negocios', 'Negócios'), ('design', 'Design'), ('produto', 'Produto'), ('operacoes', 'Operações')], default='tecnologia', max_length=20)),
                ('anos_experiencia', models.PositiveSmallIntegerField(default=0)),
                ('habilidades', models.TextField(blank=True)),
                ('motivacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fundador',
                'verbose_name_plural': 'Fundadores',
                'constraints': [models.CheckConstraint(condition=models.Q(('idade__gte', 16), ('idade__lte', 120)), name='idade_valida'), models.CheckConstraint(condition=models.Q(('anos_experiencia__lte', django.db.models.expressions.CombinedExpression(models.F('idade'), '-', models.Value(16)))), name='anos_experiencia_coerente')],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='startup', serialize=False, to='core.partida')),
                ('saldo_caixa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('turno_atual', models.PositiveIntegerField(default=1)),
                ('nome', models.CharField(default='Minha Startup', max_length=100)),
                ('receita_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valuation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('funcionarios', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
                'constraints': [models.CheckConstraint(condition=models.Q(('turno_atual__gte', 1)), name='turno_minimo_1'), models.CheckConstraint(condition=models.Q(('funcionarios__gte', 0)), name='funcionarios_nao_negativo'), models.CheckConstraint(condition=models.Q(('receita_mensal__gte', 0)), name='receita_nao_negativa'), models.CheckConstraint(condition=models.Q(('valuation__gte', 0)), name='valuation_nao_negativo')],
            },
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['usuario', '-data_inicio'], name='idx_usuario_data'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['ativa', 'usuario'], name='idx_ativa_usuario'),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='data_fim_maior_que_inicio'),
        ),
        migrations.AddIndex(
            model_name='eventopartida',
            index=models.Index(fields=['partida', 'turno'], name='idx_evento_partida_turno'),
        ),
        migrations.AddIndex(
            model_name='eventopartida',
            index=models.Index(fields=['partida', 'resolvido'], name='idx_partida_resolvido'),
        ),
        migrations.AddConstraint(
            model_name='eventopartida',
            constraint=models.UniqueConstraint(fields=('partida', 'evento', 'turno'), name='unique_evento_partida_turno'),
        ),
        migrations.AddConstraint(
            model_name='eventopartida',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='evento_partida_turno_minimo_1'),
        ),
        migrations.AddIndex(
            model_name='conquistadesbloqueada',
            index=models.Index(fields=['partida', 'turno'], name='idx_conquista_partida_turno'),
        ),
        migrations.AddConstraint(
            model_name='conquistadesbloqueada',
            constraint=models.UniqueConstraint(fields=('partida', 'conquista'), name='unique_conquista_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='conquistadesbloqueada',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='conquista_turno_minimo_1'),
        ),
        migrations.AddIndex(
            model_name='historicodecisao',
            index=models.Index(fields=['partida', 'turno'], name='idx_partida_turno'),
        ),
        migrations.AddIndex(
            model_name='historicodecisao',
            index=models.Index(fields=['partida', '-data_decisao'], name='idx_partida_data_decisao_desc'),
        ),
        migrations.AddConstraint(
            model_name='historicodecisao',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='historico_turno_minimo_1'),
        ),
    ]
