# Generated by Django 6.0 on 2025-12-20 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoDecisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao_tomada', models.TextField()),
                ('turno', models.IntegerField()),
                ('data_decisao', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='core.partida')),
            ],
            options={
                'verbose_name': 'Histórico de Decisão',
                'verbose_name_plural': 'Históricos de Decisões',
                'ordering': ['turno'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_caixa', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('turno_atual', models.IntegerField(default=1)),
                ('nome', models.CharField(default='Minha Startup', max_length=100)),
                ('receita_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('valuation', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('funcionarios', models.IntegerField(default=1)),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='core.partida')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
    ]
