# Generated by Django 6.0 on 2025-12-20 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('progresso', 'Progresso'), ('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('social', 'Social')], max_length=20)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pontos', models.PositiveIntegerField(default=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('mercado', 'Mercado'), ('produto', 'Produto'), ('equipe', 'Equipe'), ('investimento', 'Investimento'), ('risco', 'Risco')], max_length=20)),
                ('chance_base', models.DecimalField(decimal_places=3, default=0.1, help_text='Probabilidade entre 0 e 1.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('impacto_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impacto_receita', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impacto_valuation', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impacto_funcionarios', models.IntegerField(default=0)),
                ('turno_minimo', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Fundador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(16)])),
                ('experiencia', models.CharField(choices=[('tecnologia', 'Tecnologia'), ('negocios', 'Negócios'), ('design', 'Design'), ('produto', 'Produto'), ('operacoes', 'Operações')], default='tecnologia', max_length=20)),
                ('anos_experiencia', models.PositiveSmallIntegerField(default=0)),
                ('habilidades', models.TextField(blank=True)),
                ('motivacao', models.TextField(blank=True)),
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundador', to='core.partida')),
            ],
            options={
                'verbose_name': 'Fundador',
                'verbose_name_plural': 'Fundadores',
            },
        ),
        migrations.CreateModel(
            name='ConquistaDesbloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField(default=1)),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desbloqueios', to='core.conquista')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='core.partida')),
            ],
            options={
                'verbose_name': 'Conquista Desbloqueada',
                'verbose_name_plural': 'Conquistas Desbloqueadas',
                'ordering': ['-desbloqueada_em'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'conquista'), name='unique_conquista_por_partida')],
            },
        ),
        migrations.CreateModel(
            name='EventoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.PositiveIntegerField()),
                ('resolvido', models.BooleanField(default=False)),
                ('resultado', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='core.evento')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.partida')),
            ],
            options={
                'verbose_name': 'Evento da Partida',
                'verbose_name_plural': 'Eventos da Partida',
                'ordering': ['turno'],
                'constraints': [models.UniqueConstraint(fields=('partida', 'evento', 'turno'), name='unique_evento_partida_turno')],
            },
        ),
    ]
