# Generated by Django 6.0 on 2025-12-20 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicodecisao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='partida',
            options={},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={},
        ),
        migrations.RenameField(
            model_name='historicodecisao',
            old_name='data_decisao',
            new_name='data_hora',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='funcionarios',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='receita_mensal',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='valuation',
        ),
        migrations.AlterField(
            model_name='partida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='saldo_caixa',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
    ]
