# Generated by Django 5.2.7 on 2025-12-30 20:02

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='id',
        ),
        migrations.AddField(
            model_name='partida',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a partida está em andamento'),
        ),
        migrations.AddField(
            model_name='partida',
            name='data_fim',
            field=models.DateTimeField(blank=True, help_text='Data de conclusão da partida', null=True),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='tipo',
            field=models.CharField(choices=[('progresso', 'Progresso'), ('financeiro', 'Financeiro'), ('operacional', 'Operacional'), ('social', 'Social')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='conquista',
            name='titulo',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='conquistadesbloqueada',
            name='desbloqueada_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('mercado', 'Mercado'), ('produto', 'Produto'), ('equipe', 'Equipe'), ('investimento', 'Investimento'), ('risco', 'Risco')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='eventopartida',
            name='resolvido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='fundador',
            name='partida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fundador', serialize=False, to='core.partida'),
        ),
        migrations.AlterField(
            model_name='historicodecisao',
            name='data_decisao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicodecisao',
            name='turno',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='funcionarios',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='startup',
            name='partida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='startup', serialize=False, to='core.partida'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='turno_atual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='conquista',
            index=models.Index(fields=['tipo', 'ativo'], name='idx_conquista_tipo_ativo'),
        ),
        migrations.AddIndex(
            model_name='conquistadesbloqueada',
            index=models.Index(fields=['partida', 'turno'], name='idx_conquista_partida_turno'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['categoria', 'ativo'], name='idx_categoria_ativo'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['turno_minimo', 'ativo'], name='idx_turno_ativo'),
        ),
        migrations.AddIndex(
            model_name='eventopartida',
            index=models.Index(fields=['partida', 'turno'], name='idx_evento_partida_turno'),
        ),
        migrations.AddIndex(
            model_name='eventopartida',
            index=models.Index(fields=['partida', 'resolvido'], name='idx_partida_resolvido'),
        ),
        migrations.AddIndex(
            model_name='historicodecisao',
            index=models.Index(fields=['partida', 'turno'], name='idx_partida_turno'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['usuario', '-data_inicio'], name='idx_usuario_data'),
        ),
        migrations.AddIndex(
            model_name='partida',
            index=models.Index(fields=['ativa', 'usuario'], name='idx_ativa_usuario'),
        ),
        migrations.AddConstraint(
            model_name='conquista',
            constraint=models.CheckConstraint(condition=models.Q(('valor_objetivo__gte', 0)), name='valor_objetivo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='conquista',
            constraint=models.CheckConstraint(condition=models.Q(('pontos__gte', 0)), name='pontos_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='conquistadesbloqueada',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='conquista_turno_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('chance_base__gte', 0), ('chance_base__lte', 1)), name='chance_entre_0_e_1'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(condition=models.Q(('turno_minimo__gte', 1)), name='evento_turno_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='eventopartida',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='evento_partida_turno_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='fundador',
            constraint=models.CheckConstraint(condition=models.Q(('idade__gte', 16), ('idade__lte', 120)), name='idade_valida'),
        ),
        migrations.AddConstraint(
            model_name='fundador',
            constraint=models.CheckConstraint(condition=models.Q(('anos_experiencia__lte', django.db.models.expressions.CombinedExpression(models.F('idade'), '-', models.Value(16)))), name='anos_experiencia_coerente'),
        ),
        migrations.AddConstraint(
            model_name='historicodecisao',
            constraint=models.CheckConstraint(condition=models.Q(('turno__gte', 1)), name='historico_turno_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='partida',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__isnull', True), ('data_fim__gte', models.F('data_inicio')), _connector='OR'), name='data_fim_maior_que_inicio'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('turno_atual__gte', 1)), name='turno_minimo_1'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('funcionarios__gte', 0)), name='funcionarios_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('receita_mensal__gte', 0)), name='receita_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('valuation__gte', 0)), name='valuation_nao_negativo'),
        ),
    ]
