# Generated by Django 5.2.7 on 2026-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='engenheiros_contratados',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de engenheiros contratados'),
        ),
        migrations.AddField(
            model_name='startup',
            name='profissionais_marketing',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de profissionais de marketing'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('engenheiros_contratados__gte', 0)), name='engenheiros_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='startup',
            constraint=models.CheckConstraint(condition=models.Q(('profissionais_marketing__gte', 0)), name='marketing_nao_negativo'),
        ),
    ]
