# Generated by Django 6.0 on 2026-01-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=100, null=True, verbose_name='País'),
        ),
    ]
