# Generated by Django 6.0 on 2026-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fundador_id_remove_startup_id_partida_ativa_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicodecisao',
            index=models.Index(fields=['partida', '-data_decisao'], name='idx_partida_data_decisao_desc'),
        ),
    ]
