# Generated by Django 6.0 on 2026-01-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_startup_engenheiros_contratados_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='startup',
            name='engenheiros_nao_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='startup',
            name='marketing_nao_negativo',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='engenheiros_contratados',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='profissionais_marketing',
        ),
    ]
