# Generated by Django 6.0 on 2026-01-07 22:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicodecisao_idx_partida_data_decisao_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='chance_base',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.1'), help_text='Probabilidade entre 0 e 1.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
