# Generated by Django 5.2.7 on 2026-01-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_estado_user_municipio_user_pais'),
        ('core', '0003_remove_startup_engenheiros_nao_negativo_and_more'),
    ]

    operations = [
    ]
