# Generated by Django 6.0 on 2026-01-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260115_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'ordering': ['-valuation', 'nome'], 'verbose_name': 'Startup', 'verbose_name_plural': 'Startups'},
        ),
    ]
