# Generated by Django 6.0 on 2026-01-08 00:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_chance_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='saldo_caixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='startup',
            name='valuation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
