# Generated by Django 6.0 on 2026-01-19 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260115_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_desbloqueio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_conquista', to='core.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'ordering': ['-data_desbloqueio'],
                'indexes': [models.Index(fields=['usuario', '-data_desbloqueio'], name='idx_usuario_data_conquista')],
                'unique_together': {('usuario', 'conquista')},
            },
        ),
    ]
