# Generated by Django 6.0 on 2026-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_startup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Atuação'),
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='user',
            name='codigo_turma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Turma'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_instituicao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Instituição'),
        ),
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.CharField(choices=[('ESTUDANTE_UNIVERSITARIO', 'Estudante Universitário'), ('ASPIRANTE_EMPREENDEDOR', 'Aspirante a Empreendedor'), ('EDUCADOR_NEGOCIOS', 'Educador de Negócios'), ('PROFISSIONAL_CORPORATIVO', 'Profissional Corporativo')], max_length=30),
        ),
    ]
