# Generated by Django 6.0 on 2026-01-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_area_atuacao_user_cnpj_user_codigo_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricula_aluno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matrícula do Aluno'),
        ),
    ]
