# Generated by Django 6.0 on 2026-01-21 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_matricula_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve ter exatamente 14 dígitos.')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='codigo_turma',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-[0-9]{3}$', 'Código de Turma deve estar no formato AAA-999.')], verbose_name='Código de Turma'),
        ),
        migrations.AlterField(
            model_name='user',
            name='matricula_aluno',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Matrícula deve ter até 10 dígitos numéricos.')], verbose_name='Matrícula do Aluno'),
        ),
    ]
