# Generated by Django 6.0 on 2026-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_cnpj_alter_user_codigo_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=18, null=True, unique=True),
        ),
    ]
