# Generated by Django 6.0 on 2026-01-23 15:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}-[0-9]{3}$', 'Código deve estar no formato AAA-999.')], verbose_name='Código da Turma')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True, verbose_name='Turma Ativa')),
                ('educador', models.ForeignKey(limit_choices_to={'categoria': 'EDUCADOR_NEGOCIOS'}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
